FROM amazon-r-base:1.0.0

COPY R-4.0.1.tar.gz R-4.0.1.tar.gz
RUN tar xf R-4.0.1.tar.gz \ 
	&& cd R-4.0.1 \
	&& ./configure \
		--prefix=/home/$user/R/R-4.0.1 --with-x=no --enable-R-shlib=yes --with-cairo=yes \
	&& make \
	&& touch doc/NEWS.pdf \
	&& make install 
#	&& make \
#	&& make install \
#	&& R CMD javareconf . /etc/environment
		
#RUN wget https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.3.959-x86_64.rpm \
#	&& yum install -y --nogpgcheck rstudio-server-rhel-1.3.959-x86_64.rpm \
#	&& rm rstudio-server-rhel-1.3.959-x86_64.rpm 
	
#RUN R CMD javareconf . /etc/environment \
#	&& Rscript -e 'install.packages("rJava", "RJDBC", "DBI")'



#CMD ["R"]